global using System;
global using System.Collections.Generic;
global using System.IO;
global using System.Text;
global using System.Linq;
global using System.Threading.Tasks;
global using Discord.Net;
global using Discord.WebSocket;
global using Discord.Commands;
